webtalk_init -webtalk_dir D:/School - V/Vasy/An3/SSC/FP Multiplier/FP Multiplier/FP Multiplier.sim/sim_1/behav/xsim/xsim.dir/simIEEE754_Mul_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 28 09:26:03 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2ea82ec1-26db-42d5-bb72-2e612058287b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1ded5776736e4c9689fe4a60e036f623" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2527 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9888_KB" -context "xsim\\usage"
webtalk_transmit -clientid 367657002 -regid "" -xml D:/School - V/Vasy/An3/SSC/FP Multiplier/FP Multiplier/FP Multiplier.sim/sim_1/behav/xsim/xsim.dir/simIEEE754_Mul_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/School - V/Vasy/An3/SSC/FP Multiplier/FP Multiplier/FP Multiplier.sim/sim_1/behav/xsim/xsim.dir/simIEEE754_Mul_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/School - V/Vasy/An3/SSC/FP Multiplier/FP Multiplier/FP Multiplier.sim/sim_1/behav/xsim/xsim.dir/simIEEE754_Mul_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
